# Generated by Django 3.1.2 on 2020-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_destino_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('tipo_cosulta', models.IntegerField(choices=[[0, 'Seleccionar'], [1, 'Destinos'], [2, 'Atracciones'], [3, 'otros']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
