# Generated by Django 3.1.2 on 2020-11-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='tipo_cosulta',
            new_name='tipo_consulta',
        ),
    ]
