# Generated by Django 3.1.2 on 2020-11-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201124_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='pais',
            field=models.CharField(default='Chile', max_length=50),
        ),
    ]
