# Generated by Django 3.1.2 on 2020-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_destino_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='ciudad',
            field=models.CharField(default='santiago', max_length=50),
        ),
        migrations.AddField(
            model_name='destino',
            name='tipo',
            field=models.CharField(default='Monumento Historico', max_length=50),
        ),
    ]
